name: "Pull Request"
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  check-dockerfile:
    name: "Check Dockerfile"
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo.
      - name: "Checkout"
        uses: "actions/checkout@v2"

      # Prepare variables for later use.
      # https://stackoverflow.com/a/59819441
      # In testing, the trivy-action didn seem to support using $GITHUB_REPOSITORY.
      # Setting it as an output from this step allows passing the repository name
      #   to the trivy-action.
      - name: "Set Variables"
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=repo::$GITHUB_REPOSITORY"

      # Run hadolint.
      - name: "Hadolint"
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile

      # Build container image.
      - name: "Build"
        run: docker build . --file Dockerfile --tag ${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.sha_short }}

      # Use Trivy to scan the image for vulnerabilities.
      - name: "Scan Image w/ Trivy"
        uses: aquasecurity/trivy-action@master
        id: scan
        with:
          image-ref: ${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.sha_short }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
      
      # Upload scan output to Code Scanning Report.
      - name: "Upload Report"
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'