name: "Pull Request"
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  check-dockerfile:
    name: "Check Dockerfile"
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo.
      - name: "Checkout"
        uses: "actions/checkout@v2"

      # Prepare variables for later use.
      # https://stackoverflow.com/a/59819441
      # Todo: Set `name` and `id` to something more appropriate.
      - name: "Set Variables"
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # Run hadolint.
      - name: "Hadolint"
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile

      # # Build container image.
      # - name: "Build"
      #   run: docker build . --file Dockerfile --tag $GITHUB_REPOSITORY:${{ steps.vars.outputs.sha_short }}

      # - name: "Scan Image"
      #   uses: anchore/scan-action@v2
      #   with:
      #     image: $GITHUB_REPOSITORY:${{ steps.vars.outputs.sha_short }}
      
      - name: "Scan Directory"
        uses: anchore/scan-action@v2
        with:
          path: "."