name: "Update Image"
on:
  schedule:
    - cron: "*/15 * * * *"
  # Temp addition.
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  rebuild-container:
    name: "Rebuild Container"
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo.
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:

      - name: "Set Up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: Set Up Docker"
        uses: docker/setup-buildx-action@v1

      - name: "Log Into Github Registry"
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      
      - name: "Build and Push"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/$GITHUB_REPOSITORY:latest

      - name: "Image Digest"
        run: echo ${{ steps.docker_build.outputs.digest }}