name: "Update Image"
on:
  schedule:
    - cron: "*/15 * * * *"
  # Temp addition.
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  rebuild-container:
    name: "Rebuild Container"
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo.
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Build and Push"
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repoository }}/simple-monerod