name: "Update Image"
on:
  schedule:
    - cron: "0 12 * * *" # Run every day at noon.
jobs:
  rebuild-container:
    name: "Rebuild Container"
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo.
      - name: "Checkout"
        uses: "actions/checkout@v2"

      # Get tag.
      - name: "Get Tag"
        id: get_tag
        run: echo "::set-output name=tag::$(awk -F "=" '/MONERO_BRANCH=/ {print $2}' Dockerfile)"

      # Build and push the repo.
      - name: "Build and Push"
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/simple-monerod
          tags: latest, ${{ steps.get_tag.outputs.tag }}
          add_git_labels: true